### ISSUE TITLE
So where is the SOURCE CODE anyway?

### ISSUE THREAD

**Issue by erosnick** [SonyWWS/SLED#1]
I'm just looking for something like SLED, and I'm very happy I can find it. But when I read over the document about exciting features introduced by SLED, I can only find a README.md in the repository which disppointed me very much:(.

**Comment by sledpat** [comment]
Hi there,

I apologize that the code isn't there yet.  We're just waiting on the final
steps of approval, and then it'll be up.  I'll send an email when it's
finally up.  Again, sorry.

-Patrick

**Comment by erosnick** [comment]
Hi, Patrick, thanks for the quick reply:).
I'm really looking forward to it.
Thanks again for your great work to make such awesome toolsets and bring them to public.

**Comment by philpax** [comment]
We're interested in providing a Lua IDE to our game's scripters, and SLED looks like what we're looking for. Is there any news you can provide as to where the approval process is at? Any information you can provide would be much appreciated.

**Comment by sledpat** [comment]
We're so close to having the source approved from way up. I'm sorry it's
taken so long. It's quite embarrassing.

**Comment by sledpat** [comment]
Apologies for the delays, but the code is up.

https://github.com/SonyWWS/SLED.git

-Patrick

**Comment by erosnick** [comment]
WOW, finally it's here,thanks alot! :)
