### ISSUE TITLE
No <sce_sled/sled.h>?

### ISSUE THREAD

**Issue by erosnick** [SonyWWS/SLED#2]
I found that there is no sce_sled/sled.h directory structure in source, but it seems that  using sled.h in the solution root folder just works fine?

**Comment by sledpat** [comment]
Ah, sorry, I see what you mean. This is an artifact of how the source is set up in a different repository where it lives alongside a ton of other things. In that repository, everything's broken up into various components/projects, and for this open source release I had to kludge everything together.

I recommend cloning the source into a directory that's side-by-side your project-
- <some root or common directory that holds source code>\
  - <your project>\
  - SledOSS\

Then you can have that common directory be an include path and **#include <SledOSS/sled.h>** will work.  This also lets you have multiple projects that come from multiple git/SVN sources all live side by side w/o them trouncing each others' .git/.svn folders.

**Comment by erosnick** [comment]
OK, I got things up and running, thanks a lot. :)
