### ISSUE TITLE
Why no source for sledcore?

### ISSUE THREAD

**Issue by amerkoleci** [SonyWWS/SLED#3]
I saw sledcore comes only with libraries, I would like to port some stuff on different platforms than windows.

**Comment by sledpat** [comment]
Thanks for your comment.  As far as I'm aware, I'm not allowed to release the source that makes up _sledcore_.  The implementation details are pretty straightforward, though, if you just wanted to write your own _sledcore_ altogether.

**Comment by amerkoleci** [comment]
Ok then, closing... Thank you

**Comment by sledpat** [comment]
I should mention I'll happily accept pull requests for other platforms.  (Just be smart in the naming as SLED comes from Sony...)
